spring.application.name=classificados-ifsc

# CONEXÃO COM O BANCO
spring.datasource.url=jdbc:postgresql://localhost:5432/classificados_db?createDatabaseIfNotExist=true
spring.datasource.username=postgres
# APAGUE 'sua_senha' ABAIXO E DIGITE A SENHA QUE VOCÊ CRIOU NO POSTGRES
spring.datasource.password=sua_senha

# DICA DE OURO DO PROFESSOR (GERAÇÃO AUTOMÁTICA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect